version: '3.5'

services:
  negocio-fechado:
    build: .
    container_name: negocio-fechado
    ports:      
      - "9000:80"
    restart: unless-stopped
    volumes:
      - ./app:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./supervisord.conf:/etc/supervisord.conf
    environment:          
      SECRET_KEY: "IO456JHUI456HIO456U566PO6K4OP64UY6U5YG6U5I464UI56U464"
  