# Generated by Django 2.2.9 on 2020-05-09 15:15

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import negocio_fechado.models.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Needs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('price', models.CharField(max_length=255, verbose_name='Valor')),
                ('state', models.CharField(choices=[(1, 'Recente'), (2, 'Com proposta'), (3, 'Em negociação'), (4, 'Falta assinar'), (5, 'Em execução'), (6, 'Finalizado')], max_length=255, verbose_name='Estado')),
                ('files', models.FileField(upload_to='attachments/%Y/%m/%d/', verbose_name='Anexos')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('price', models.CharField(max_length=255, verbose_name='Valor')),
                ('state', models.CharField(choices=[(1, 'Recente'), (2, 'Com proposta'), (3, 'Em negociação'), (4, 'Falta assinar'), (5, 'Em execução'), (6, 'Finalizado')], max_length=255, verbose_name='Estado')),
                ('files', models.FileField(upload_to='attachments/%Y/%m/%d/', verbose_name='Anexos')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=32, verbose_name='Senha')),
                ('first_name', models.CharField(max_length=45, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=45, verbose_name='Sobrenome')),
                ('photo', models.FileField(blank=True, max_length=255, null=True, upload_to='', verbose_name='Foto do perfil')),
                ('birth_date', models.DateField(max_length=255, verbose_name='Data de nascimento')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='CPF')),
                ('type', models.CharField(choices=[('WORKER', 'Prestador de serviço.'), ('CONSUMER', 'Consumidor.')], max_length=255, verbose_name='Tipo')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', negocio_fechado.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('price', models.CharField(max_length=255, verbose_name='Valor')),
                ('state', models.CharField(choices=[(1, 'Enviada'), (2, 'Aceita'), (3, 'Recusada')], max_length=255, verbose_name='Senha')),
                ('needs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='negocio_fechado.Needs')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='negocio_fechado.Offer')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocio_fechado.User')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocio_fechado.User'),
        ),
        migrations.AddField(
            model_name='needs',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocio_fechado.User'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rules', models.TextField(blank=True, null=True, verbose_name='Regras')),
                ('state', models.CharField(choices=[(1, 'Aberto'), (2, 'Fechado'), (3, 'Aceito pelo consumidor'), (4, 'Aceito pelo prestador'), (5, 'Aceito por ambos')], max_length=255, verbose_name='Estado')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractor', to='negocio_fechado.User')),
                ('hired', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hired', to='negocio_fechado.User')),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='negocio_fechado.Tender')),
            ],
        ),
    ]
