# Generated by Django 2.2.9 on 2020-05-01 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Senha')),
                ('description', models.CharField(max_length=255, verbose_name='Senha')),
                ('offer', models.CharField(max_length=255, verbose_name='Senha')),
                ('needs', models.CharField(max_length=255, verbose_name='Senha')),
                ('price', models.CharField(max_length=255, verbose_name='Senha')),
                ('state', models.CharField(max_length=255, verbose_name='Senha')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('password', models.CharField(max_length=32, verbose_name='Senha')),
                ('first_name', models.CharField(max_length=45, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=45, verbose_name='Sobrenome')),
                ('photo', models.FileField(max_length=255, upload_to='', verbose_name='Foto do perfil')),
                ('birth_date', models.DateField(max_length=255, verbose_name='Idade')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('type', models.CharField(choices=[('WORKER', 'Prestador de serviço.'), ('CONSUMER', 'Consumidor.')], max_length=255, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('price', models.CharField(max_length=255, verbose_name='Valor')),
                ('state', models.CharField(choices=[(1, 'Recente'), (2, 'Com proposta'), (3, 'Em negociação'), (4, 'Falta assinar'), (5, 'Em execução'), (6, 'Finalizado')], max_length=255, verbose_name='Estado')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocio_fechado.User')),
            ],
        ),
        migrations.CreateModel(
            name='Needs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('price', models.CharField(max_length=255, verbose_name='Valor')),
                ('state', models.CharField(choices=[(1, 'Recente'), (2, 'Com proposta'), (3, 'Em negociação'), (4, 'Falta assinar'), (5, 'Em execução'), (6, 'Finalizado')], max_length=255, verbose_name='Estado')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocio_fechado.User')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rules', models.TextField(blank=True, null=True, verbose_name='Regras')),
                ('state', models.CharField(choices=[(1, 'Aberto'), (2, 'Fechado'), (3, 'Aceito pelo consumidor'), (4, 'Aceito pelo prestador'), (5, 'Aceito por ambos')], max_length=255, verbose_name='Estado')),
                ('needs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='negocio_fechado.Needs')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='negocio_fechado.Offer')),
            ],
        ),
    ]
