# Generated by Django 2.2.9 on 2020-05-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio_fechado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needs',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/', verbose_name='Anexos'),
        ),
    ]
