# Generated by Django 2.2.9 on 2020-05-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio_fechado', '0002_auto_20200509_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/', verbose_name='Anexos'),
        ),
    ]
