# Generated by Django 2.2.9 on 2020-05-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio_fechado', '0004_auto_20200517_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/', verbose_name='Arquivo')),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='files',
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='avatar/%Y/%m/%d/', verbose_name='Foto do perfil'),
        ),
        migrations.AddField(
            model_name='offer',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='negocio_fechado.File'),
        ),
    ]
